name: 'EH CI Summary Builder'
description:
  'A Github Action to build CI Summary for a pull request using Handlebars
  templates for EH'
author: 'tult98'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'file'
  color: 'blue'

# Define your inputs here.
inputs:
  init-json-file-path:
    description: 'Path to the JSON file to initialize the CI summary.'
    required: false
  name:
    description: 'The name of the workflow that need to be reported'
    required: false
  required:
    description: 'Whether the workflow is required or optional'
    required: false
  status:
    description: 'The status of the workflow'
    required: false
  html-url:
    description: 'The URL of the workflow run'
    required: false
  errors:
    description: 'The errors of the workflow run'
    required: false
  pull-request:
    description: 'Create a pull request comment or not'
    required: false
    default: true

# Define your outputs here, if necessary.
outputs:
  summary:
    description: 'The generated markdown summary.'

# Specify the environment and entry point for the action.
runs:
  using: 'node20'
  main: dist/index.js
